use Mix.Config

# For production, don't forget to configure the url host
# to something meaningful, Phoenix uses this information
# when generating URLs.
#
# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix phx.digest` task,
# which you should run after static files are built and
# before starting your production server.
config :np, NpWeb.Endpoint,
  http: [ 
    ip: elem(:inet.parse_address(to_charlist(System.get_env("ALWAYSDATA_HTTPD_IP"))), 1), 
    port: System.get_env("ALWAYSDATA_HTTPD_PORT") 
  ],
  url: [host: System.get_env("HOSTNAME"), port: 80],
  cache_static_manifest: "priv/static/cache_manifest.json"

# Do not print debug messages in production
config :logger, level: :info

import_config "prod.secret.exs"
